baseURL = "https://pljakobs.github.io/ichWillDasNicht/"
languageCode = "en-us"
title = "A stack of letters"
theme = "PaperMod"

[module]
[[module.imports]]
  path = "github.com/adityatelange/hugo-PaperMod"

[params]
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  [params.homeInfoParams]
    Title = "A Stack of Letters"
    Content = "Welcome to my collection of letters."
